<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\{
    FromCollection,
    WithHeadings,
    WithStyles,
    WithEvents,
    WithCustomStartCell
};
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Maatwebsite\Excel\Events\AfterSheet;
use Illuminate\Support\Collection;
use Carbon\Carbon;

class BookingExport implements FromCollection, WithHeadings, WithStyles, WithEvents, WithCustomStartCell
{
    protected $data;
    protected $startDate;
    protected $endDate;

    public function __construct(Collection $data, $startDate = null, $endDate = null)
    {
        $this->data = $data;
        $this->startDate = $startDate;
        $this->endDate = $endDate;
    }

    public function startCell(): string
    {
        return 'A6';
    }

    public function styles(Worksheet $sheet)
    {
        return [
            6 => ['font' => ['bold' => true]],
        ];
    }

    public function collection()
    {
        return $this->data->map(function ($item, $index) {

            $approval = $item->approvals->map(function ($a) {
                return "L{$a->level} - {$a->approver->name} (" . ucfirst($a->status) . ")";
            })->implode("\n");

            return [
                $index + 1,
                $item->vehicle->plate_number,
                ucfirst($item->vehicle->type),
                $item->driver->name,
                $item->driver->phone,
                $item->requester->name ?? '-',
                Carbon::parse($item->start_date)->format('d M Y'),
                Carbon::parse($item->end_date)->format('d M Y'),
                $item->purpose,
                $approval,
                ucfirst(str_replace('_', ' ', $item->status)),
            ];
        });
    }

    public function headings(): array
    {
        return [
            'No',
            'Vehicle',
            'Type',
            'Driver',
            'Driver Phone',
            'Requester',
            'Start Date',
            'End Date',
            'Purpose',
            'Approval',
            'Status',
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function ($event) {

                $sheet = $event->sheet;

                $appName = config('app.name');

                // HEADER
                $sheet->setCellValue('A1', $appName);
                $sheet->mergeCells('A1:K1');

                $sheet->setCellValue('A2', 'Laporan Pemesanan Kendaraan');
                $sheet->mergeCells('A2:K2');

                $sheet->setCellValue('A3', 'Tanggal Cetak: ' . now()->format('d M Y H:i'));
                $sheet->mergeCells('A3:K3');

                $periode = ($this->startDate && $this->endDate)
                    ? $this->startDate . ' s/d ' . $this->endDate
                    : 'Semua Data';

                $sheet->setCellValue('A4', 'Periode: ' . $periode);
                $sheet->mergeCells('A4:K4');

                $sheet->setCellValue('A5', 'Total Data: ' . $this->data->count());
                $sheet->mergeCells('A5:K5');

                // STYLE HEADER
                $sheet->getStyle('A1:A2')->getFont()->setBold(true)->setSize(14);
                $sheet->getStyle('A1:A5')->getAlignment()->setHorizontal('center');

                // AUTO WIDTH
                foreach (range('A', 'K') as $col) {
                    $sheet->getColumnDimension($col)->setAutoSize(true);
                }

                // WRAP TEXT (biar approval kebaca)
                $sheet->getStyle('J')->getAlignment()->setWrapText(true);

                // FOOTER
                $lastRow = $sheet->getHighestRow() + 2;

                $sheet->setCellValue("A{$lastRow}", 'Generated by ' . $appName);
                $sheet->setCellValue("A" . ($lastRow + 1), '© ' . date('Y') . ' ' . $appName);
            },
        ];
    }
}
