<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: sans-serif;
            font-size: 11px;
            position: relative;
        }

        /* WATERMARK */
        .watermark {
            position: fixed;
            top: 40%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-30deg);
            font-size: 60px;
            color: rgba(0, 0, 0, 0.05);
            z-index: -1;
            white-space: nowrap;
        }

        .header {
            text-align: center;
            margin-bottom: 10px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 0;
        }

        .info {
            margin-bottom: 10px;
            font-size: 11px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
        }

        .table th,
        .table td {
            border: 1px solid #000;
            padding: 5px;
            vertical-align: top;
        }

        .table th {
            background: #eee;
            text-align: center;
        }

        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: right;
        }
    </style>
</head>

<body>

    <!-- WATERMARK -->
    <div class="watermark">
        {{ config('app.name') }}
    </div>

    <!-- HEADER -->
    <div class="header">
        <h2>{{ config('app.name') }}</h2>
        <p><b>LAPORAN PEMESANAN KENDARAAN</b></p>
    </div>

    <!-- INFO -->
    <div class="info">
        <p>Tanggal Cetak: {{ \Carbon\Carbon::now()->format('d M Y H:i') }}</p>

        <p>
            Periode:
            {{ $start_date ?? '-' }} s/d {{ $end_date ?? '-' }}
        </p>

        <p>Total Data: {{ $data->count() }}</p>
        <p>Total Completed: {{ $data->where('status', 'completed')->count() }}</p>
    </div>

    <!-- TABLE -->
    <table class="table">
        <thead>
            <tr>
                <th>No</th>
                <th>Vehicle</th>
                <th>Driver</th>
                <th>Requester</th>
                <th>Periode</th>
                <th>Purpose</th>
                <th>Approval</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $i => $item)
                <tr>
                    <td>{{ $i + 1 }}</td>

                    <td>
                        {{ $item->vehicle->plate_number }}<br>
                        <small>{{ ucfirst($item->vehicle->type) }}</small>
                    </td>

                    <td>
                        {{ $item->driver->name }}<br>
                        <small>{{ $item->driver->phone }}</small>
                    </td>

                    <td>
                        {{ $item->requester->name ?? '-' }}<br>
                        <small>{{ $item->requester->email ?? '' }}</small>
                    </td>

                    <td>
                        {{ \Carbon\Carbon::parse($item->start_date)->format('d M Y') }}<br>
                        s/d<br>
                        {{ \Carbon\Carbon::parse($item->end_date)->format('d M Y') }}
                    </td>

                    <td>{{ $item->purpose }}</td>

                    <td>
                        @foreach ($item->approvals as $a)
                            <div>
                                <b>L{{ $a->level }}</b> -
                                {{ $a->approver->name ?? '-' }}
                                ({{ ucfirst($a->status) }})
                            </div>
                        @endforeach
                    </td>

                    <td>
                        <b>{{ ucfirst(str_replace('_', ' ', $item->status)) }}</b>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
        <p>© {{ date('Y') }} {{ config('app.name') }}</p>
    </div>

    <!-- SIGNATURE -->
    <div style="margin-top: 50px; width: 100%;">
        <table width="100%">
            <tr>
                <td style="text-align: left;">
                    Mengetahui,<br><br><br><br>
                    _______________________<br>
                    Manager Operasional
                </td>
                <td style="text-align: right;">
                    Dibuat oleh,<br><br><br><br>
                    _______________________<br>
                    Admin
                </td>
            </tr>
        </table>
    </div>

</body>

</html>
